[package]
name = "server"
version = "0.1.0"
authors = ["Jonathan Li <30177086+MonliH@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.3"
lazy_static = "1.4.0"
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4.18", features = ["serde"] }
serde_yaml = "0.8"
